# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FahadDeVCrewAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FahadDeVCrewAssignment
  pod 'SwiftyJSON', '~> 4.0'

end
